### ISSUE TITLE
Cannot Reconnect

### ISSUE THREAD

**Issue by ashbrindle** [erra-changer/team_project#1]
Cannot connect after restarting display app.
**recreate issue:**
- [x] 1. launch both apps
- [x] 2. connect normally
- [x] 3. close display app, keep other running
- [x] 4. try to reconnect on display app

**Comment by she-bytes** [comment]
I am unable to recreate this issue. The only problem that can occur is if the display app connects to the simulator and the data has already changed, the display app will not show it. Going to work on that now.

**Comment by she-bytes** [comment]
I have updated my code so that each time a device connects, a notification for each characteristic is immediately sent. You should be able to recieve this data on connection now. Can you take a look and see if you can get this working from your end now?

**Comment by ashbrindle** [comment]
My application now accepts your default data, however your app does not send the correct default values, could you look at this on your end. For example; Indicator set to left (1) by default

**Comment by she-bytes** [comment]
Done.
