### ISSUE TITLE
Enable Bluetooth Prompt

### ISSUE THREAD

**Issue by ashbrindle** [erra-changer/team_project#5]
Consider adding a prompt for asking the user to enable bluetooth in app if adapter is disabled.

**Comment by she-bytes** [comment]
Takes user prompt and does not proceed if declined. Need to add functionality to continue process if accepted however. As right now if the user presses accept, bluetooth is enabled, but user must select start again.

**Comment by she-bytes** [comment]
Also needs quality of life update: 

If location is not enabled, both prompts pop up at the same time.
